allowBuilds:
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@microsoft/api-extractor-model@7.33.9'
  - '@microsoft/api-extractor@7.58.10'
  - '@rushstack/node-core-library@5.23.2'
  - '@rushstack/terminal@0.24.1'
  - '@rushstack/ts-command-line@5.3.11'
  - vite@8.1.5
